const letrasMixtape = [
  // 1. Letra de 01.txt
  "Tudo fica mais bonito quando você está por perto\nVocê me levou ao delírio por isso eu confesso\nOs seus beijos são ardentes\nQuando você se aproxima o meu corpo sente\nOs seus beijos são ardentes\nQuando você se aproxima o meu corpo sente\n\nVem pra cá deusa do amor\nVejam o bloco Olodum ao passar na avenida\nTodos cantando felizes de bem com a vida\nCaminhando lado a lado\nFormamos um belo casal somos dois namorados\nNo swing dessa banda\n\nBalança o mais forte alicerce que tem neste mundo\nO cupido me flechou\nFoi no bloco Olodum que encontrei meu amor\nVem pra cá deusa do amor\nVem me embalar, neném\n\n",
  // 2. Letra de 02.txt
  "Você me mostrou que o amor pode ser fácil\nE eu desconfiei\nNunca tinha visto a paz tão perto do meu nariz\nEu pensei que pra ser feliz, o chão precisava tremer\nE a realidade parecer mentira, que coisa boba\nEncontrei, nas besteiras da rotina, a maior beleza\n\nVocê me falou o seu amor no meu ouvido\nSem pedir de volta uma resposta, garantia ou coisa assim\nTão diferente de mim, tão longe das explosões\nSem preocupar com os dias que virão\n\nQue coisa boa ter o coração no chão\nE ter coragem pra dizer\nEu te amo\nE eu te amo\n\nDo jeito mais simples e bonito\nNão sei o que vem depois, nem os riscos\nTô deixando o corpo escolher o caminho da vontade\nE a vontade tem sido você, tem sido você toda hora\nSó você\n\nQue venham as surpresas, os atrasos, os abismos, os desencontros\nDesafios, canastras, perigos\nQue sinalizem astros, profecias, as intuições e os guias espirituais\nAs intuições e os guias espirituais\nAs intuições e os guias\n\nEu quero estar contigo\nE nada mais\nE nada mais\nEu quero estar contigo\nE nada mais",
  // 3. Letra de 03.txt
  "Quer me deixar\nNão sei porquê\nDeixa eu pensar\nPra sei lá, ver\nO que fazer\nPra você ficar?\n\nSem seu amor\nA vida passa em vão\nSe você for\nO que é de vidro quebra\nNo meu coração\nSeu olhar é lindo\nVer você sorrindo\nÉ demais\nPor favor não faz\nMe dizer adeus\nVai me botar a perder\n\nTenha calma\nNão se vá meu pop star\nTenha fé\nTe prometo vir a ser\nDo jeito que você quer\nUm amor de mulher\n\nMeu amor\nMeu amor nunca\nTe ausentes de mim\nPara que eu viva em paz\nPara que eu não sofra mais\nTanta mágoa assim\nNum mundo sem você",
  // 4. Letra de 04.txt
  "A selva toda iluminada\nE eu só lembro\nDa luz que era a tua e não elétrica\nDo ar que me fugia em cada sílaba\nEu viajava no teu papo quântico\n\nTu me engolia com essa cara cínica\nE eu vigiava com meu olho míope\nTentei caber na tua matemática\n\nQuantos encontros cabem numa vida?\nQuantas vidas pra viver?\nQuanto chão pra caminhar?\nQuantos sóis nós vamos ver nascer?\nMundos vão ruir\nCuras vão surgir\nE nós dois aqui\n\nTua cadência embriagada\nEu entendo\nTe confiei as minhas crenças cármicas\nVocê cantou pra mim a tua dúvida\nTua praia cética, minha onda mística\n\nFantasiei o teu lugar mais íntimo\nTe respondi no meu lugar mais úmido\nCriamos pontes sobre amores líquidos\n\nQuantos encontros cabem numa vida?\nQuantas vidas pra viver?\nQuanto chão pra caminhar?\nQuantos sóis nós vamos ver nascer?\nMundos vão ruir\nCuras vão surgir\nE nós dois aqui",
  // 5. Letra de 05.txt
  "Agulhas pra fazer crochê\nTecer um cheiro, costurar você\nNo emaranhado do final do dia\nDá saudade\nPonto a ponto até chegar no fio\nDançar a dois ou costurar um rio\nNo pensamento\n\nPensei que mandar um poema daria o tom\nTalvez uma colcha, retalhar mais um sonho bom\nFicar à vontade pra poder me esparramar\nE sorrir sem maldar ao teu lado\n\nPensei que mandar um poema daria o tom\nTalvez uma colcha, retalhar mais um sonho bom\nFicar à vontade pra poder me esparramar\nE sorrir sem maldar ao teu lado\n\nAgulhas pra fazer crochê\nTecer um cheiro, costurar você\nNo emaranhado do final do dia\nDá saudade\nPonto a ponto até chegar no fio\nDançar a dois ou costurar um rio\nNo pensamento, uh\n\nPensei que mandar um poema daria o tom\nTalvez uma colcha, retalhar mais um sonho bom\nFicar à vontade pra poder me esparramar\nE sorrir sem maldar ao teu lado\n\nPensei que mandar um poema daria o tom\nTalvez uma colcha, retalhar mais um sonho bom\nFicar à vontade pra poder me esparramar\nE sorrir sem maldar ao teu lado\n\nPensei que mandar um poema daria o tom\nTalvez uma colcha, retalhar mais um sonho bom\nFicar à vontade pra poder me esparramar...",
  // 6. Letra de 06.txt
  "Fomos felizes e felizes fomos\nE se já não somos, meu amor\nNão se preocupe, não\nAperte a minha mão\nAté a luz sumir\nEm meio à escuridão\nVocê vai confiar em mim\n\nGuarde um pedaço de mim\nUm cheiro no lado da cama\nSeu gosto na ponta do queixo\nMeu sangue escorrendo seu peito\n\nVejo no tato sua pele\nTatuo com dedo o seu gosto\nNão sigo mapas, desejo\nSegredo e contato\n\nQuero o brilho cortante\nDesses cacos de vidro\nPalavras no corpo\nRespostas ao vento\n\nVocê diz pra não falar de amor\nE me pede pra fechar os olhos\nEsquecer, amor\nPoucos versos são precisos\n\nNinguém diz eu te amo\nNinguém diz eu te amo\nNinguém diz eu te amo\nComo eu\n\nNinguém diz eu te amo\nNinguém diz eu te amo\nNinguém diz eu te amo\nComo eu\n\nNinguém diz eu te amo\nNinguém diz eu te amo\nComo eu, como eu\n\nNinguém diz eu te amo\nNinguém diz eu te amo\nComo eu, como eu\nNinguém diz melhor\n\nNinguém diz eu te amo\nNinguém diz, ninguém diz\nEu te amo como eu, como eu",
  // 7. Letra de 07.txt
  "(Uh-uh-uh)\n\nÉ incrível\nNada desvia o destino\nHoje, tudo faz sentido\nE ainda há tanto a aprender\n\nE a vida\nTão generosa comigo\nVeio, de amigo a amigo\nMe apresentar a você\n\nParalisa\nCom seu olhar, Monalisa\nSeu quase rir ilumina\nTudo ao redor, minha vida\nAi de mim, me conduza\nJunto a você ou me usa\nPro seu prazer, me fascina\nDeusa com ar de menina\n\nNão se prenda\nA sentimentos antigos\nTudo que se foi vivido\nMe preparou pra você\n\nNão se ofenda\nCom meus amores de antes\nTodos tornaram-se ponte\nPra que eu chegasse a você, ei\n\nParalisa\nCom seu olhar, Monalisa\nE, ao quase rir, ilumina\nTudo ao redor, minha vida\nAi de mim, me conduza\nJunto a você ou me usa\nPro seu prazer, me fascina\nDeusa com ar de menina\n\nParalisa\nCom seu olhar, Monalisa\nE, ao quase rir, ilumina\nTudo ao redor, minha vida\nMe conduza\nLá junto a você ou me usa\nPro seu prazer, me fascina\nDeusa com ar de menina\n\nMe fascina\nDeusa com ar de menina",
  // 8. Letra de 08.txt
  "Há um vilarejo ali\nOnde areja um vento bom\nNa varanda, quem descansa\nVê o horizonte deitar no chão\n\nPra acalmar o coração\nLá o mundo tem razão\nTerra de heróis, lares de mãe\nParaíso se mudou para lá\n\nPor cima das casas, cal\nFrutas em qualquer quintal\nPeitos fartos, filhos fortes\nSonhos semeando o mundo real\n\nToda gente cabe lá\nPalestina, Xangri-Lá\nVem andar e voa\nVem andar e voa\nVem andar e voa\n\nLá o tempo espera\nLá é primavera\nPortas e janelas\nFicam sempre abertas\nPra sorte entrar\n\nEm todas as mesas, pão\nFlores enfeitando\nOs caminhos, os vestidos\nOs destinos e essa canção\nTem um verdadeiro amor\nPara quando você for\n\nHá um vilarejo ali\nOnde areja um vento bom\nNa varanda, quem descansa\nVê o horizonte deitar no chão\n\nPra acalmar o coração\nLá o mundo tem razão\nTerra de heróis, lares de mãe\nParaíso se mudou para lá\n\nPor cima das casas, cal\nFrutas em qualquer quintal\nPeitos fartos, filhos fortes\nSonhos semeando o mundo real\n\nToda gente cabe lá\nPalestina, Xangri-Lá\nVem andar e voa\nVem andar e voa\nVem andar e voa\n",
  // 9. Letra de 09.txt
  "I wanna be your vacuum cleaner\nBreathing in your dust\nI wanna be your Ford Cortina\nI will never rust\n\nIf you like your coffee hot\nLet me be your coffee pot\nYou call the shots, babe\nI just wanna be yours\n\nSecrets I have held in my heart\nAre harder to hide than I thought\nMaybe I just wanna be yours\nI wanna be yours, I wanna be yours\n\nWanna be yours\nWanna be yours\nWanna be yours\n\nLet me be your 'leccy meter\nAnd I'll never run out\nLet me be the portable heater\nThat you'll get cold without\n\nI wanna be your setting lotion (wanna be)\nHold your hair in deep devotion (how deep?)\nAt least as deep as the Pacific Ocean\nI wanna be yours\n\nSecrets I have held in my heart\nAre harder to hide than I thought\nMaybe I just wanna be yours\nI wanna be yours, I wanna be yours\n\nWanna be yours\nWanna be yours\nWanna be yours\nWanna be yours\n\nWanna be yours\nWanna be yours\nWanna be yours\nWanna be yours\n\nI wanna be your vacuum cleaner (wanna be yours)\nBreathing in your dust (wanna be yours)\nI wanna be your Ford Cortina (wanna be yours)\nI will never rust (wanna be yours)\n\nI just wanna be yours (wanna be yours)\nI just wanna be yours (wanna be yours)\nI just wanna...",
  // 10. Letra de 10.txt
  "O que há dentro do meu coração\nEu tenho guardado pra te dar\nE todas as horas que o tempo tem pra me conceder\nSão tuas, até morrer\n\nE a tua história, eu não sei\nMas me diga só o que for bom\nUm amor tão puro que ainda nem sabe a força que tem\nÉ teu e de mais ninguém\n\nTe adoro em tudo, tudo, tudo\nQuero mais que tudo, tudo, tudo\nTe amar sem limites, viver uma grande história\nTe adoro em tudo, tudo, tudo\nQuero mais que tudo, tudo, tudo\nTe amar sem limites, viver uma grande história\n\nAqui ou noutro lugar\nQue pode ser feio ou bonito\nSe nós estivermos juntos\nHaverá um céu azul, oh\n\nUm amor puro\nNão sabe a força que tem\nMeu amor, eu juro\nSer teu e de mais ninguém\nUm amor puro\n\nO que há dentro do meu coração\nEu tenho guardado pra te dar\nE todas as horas que o tempo tem pra me conceder\nSão tuas, até morrer\n\nE a tua história, eu não sei\nMas me diga só o que for bom\nUm amor tão puro que ainda nem sabe a força que tem\nÉ teu e de mais ninguém\n\nTe adoro em tudo, tudo, tudo\nQuero mais que tudo, tudo, tudo\nTe amar sem limites, viver uma grande história\nTe adoro em tudo, tudo, tudo\nQuero mais que tudo, tudo, tudo\nTe amar sem limites, viver uma grande história\n\nTe adoro...",
  // 11. Letra de 11.txt
  "Se você vier\nPro que der e vier\nComigo\nEu lhe prometo o Sol\nSe hoje o Sol sair\nOu a chuva\nSe a chuva cair\n\nSe você vier\nAté onde a gente chegar\nNuma praça, na beira do mar\nNum pedaço de qualquer lugar\n\nNesse dia branco\nSe branco ele for\nEsse tanto, esse canto de amor, oh\nSe você quiser e vier\nPro que der e vier\nComigo\n\nSe você vier\nPro que der e vier\nComigo\nEu lhe prometo o Sol\nSe hoje o Sol sair\nOu a chuva\nSe a chuva cair\n\nSe você vier\nAté onde a gente chegar\nNuma praça, na beira do mar\nNum pedaço de qualquer lugar\n\nE nesse dia branco\nSe branco ele for\nEsse canto\nEsse tão grande amor\nGrande amor\nSe você quiser e vier\nPro que der e vier\nComigo\n\nComigo\nComigo",
  // 12. Letra de 12.txt
  "Ainda bem\nQue você vive comigo\nPorque senão\nComo seria esta vida?\nSei lá, sei lá\n\nNos dias frios em que nós estamos juntos\nNos abraçamos sob o nosso conforto\nDe amar, de amar\n\nSe há dores, tudo fica mais fácil\nSeu rosto silencia e faz parar\nAs flores que me manda são fato\nDo nosso cuidado e entrega\n\nMeus beijos sem os seus, não dariam\nOs dias chegariam sem paixão\nMeu corpo sem o seu, uma parte\nSeria o acaso e não sorte\n\nAinda bem\nQue você vive comigo\nPorque senão\nComo seria esta vida?\nSei lá, sei lá\n\nSe há dores, tudo fica mais fácil\nSeu rosto silencia e faz parar\nAs flores que me manda são fato\nDo nosso cuidado e entrega\n\nMeus beijos sem os seus, não dariam\nOs dias chegariam sem paixão\nMeu corpo sem o seu, uma parte\nSeria o acaso e não sorte\n\nNeste mundo de tantos anos\nEntre tantos outros\nQue sorte a nossa, hein?\nEntre tantas paixões\nEsse encontro, nós dois, esse amor\n\nEntre tantos anos\nEntre tantos outros\nQue sorte a nossa, hein?\nEntre tantas paixões\nEsse encontro, nós dois, esse amor\n\nEntre tantas paixões\nEsse encontro, nós dois, esse amor",
  // 13. Letra de 13.txt
  "Quando não tinha nada, eu quis\nQuando tudo era ausência, esperei\nQuando tive frio, tremi\nQuando tive coragem, liguei\n\nQuando chegou carta, abri\nQuando ouvi Prince, dancei\nQuando o olho brilhou, entendi\nQuando criei asas, voei\n\nQuando me chamou, eu vim\nQuando dei por mim, tava aqui\nQuando lhe achei, me perdi\nQuando vi você, me apaixonei\n\nÔ, amarrara dzaia soiê, dzaia, dzaia\nAí, iii, iinga dunrã\nOooh!\nÔ, amarrara dzaia soiê, dzaia, dzaia\nAí, iii, iinga dunrã\n\nQuando não tinha nada, eu quis\nQuando tudo era ausência, esperei\nQuando tive frio, tremi\nQuando tive coragem, liguei\n\nQuando chegou carta, abri\nQuando ouvi Salif Keita, dancei\nQuando o olho brilhou, entendi\nQuando criei asas, voei\n\nQuando me chamou, eu vim\nQuando dei por mim, tava aqui\nQuando lhe achei, me perdi\nQuando vi você, me apaixonei\n\nÔ, amarrara dzaia soiê, dzaia, dzaia\nAí, iii, iinga dunrã\nOooh!\nÔ, amarrara dzaia soiê, dzaia, dzaia\nAí, iii, iinga dunrã\n\nQuando...",
  // 14. Letra de 14.txt
  "Georgia\nWrap me up in all your, I want ya\nIn my arms, oh, let me hold ya\nI'll never let you go again like I did\nOh, I used to say\n\nI would never fall in love again until I found her\nI said I would never fall unless it's you I fall into\nI was lost within the darkness, but then I found her\nI found you\n\nGeorgia\nPulled me in, I asked to love her\nOnce again you fell, I caught ya\nI'll never let you go again like I did\nOh, I used to say\n\nI would never fall in love again until I found her\nI said I would never fall unless it's you I fall into\nI was lost within the darkness, but then I found her\nI found you\n\nI would never fall in love again until I found her\nI said I would never fall unless it's you I fall into\nI was lost within the darkness, but then I found her\nI found you",
  // 15. Letra de 15.txt
  "Eu quero me esconder debaixo\nDessa sua saia pra fugir do mundo\nPretendo também me embrenhar\nNo emaranhado desses teus cabelos\nPreciso transfundir teu sangue\nPro meu coração que é tão vagabundo\n\nMe deixe te trazer num dengo\nPra num cafuné fazer os meus apelos\nMe deixe te trazer num dengo\nPra num cafuné fazer os meus apelos\n\nEu quero ser exorcizado\nPela água benta desse olhar infindo\nQue bom é ser fotografado\nMas pela retina desses olhos lindos\nMe deixe hipnotizado\nPra acabar de vez com essa disritmia\n\nVem logo, vem curar teu nego\nQue chegou de porre lá da boemia\nVem logo, vem curar teu nego\nQue chegou de porre lá da boemia\n\nEu quero me esconder debaixo\nDessa tua saia pra fugir do mundo\nPretendo também me embrenhar\nNo emaranhado desses teus cabelos\nPreciso transfundir teu sangue\nPro meu coração que é tão vagabundo\n\nMe deixe te trazer num dengo\nPra num cafuné fazer os meus apelos\nMe deixe te trazer num dengo\nPra num cafuné fazer os meus apelos\n\nEu quero ser exorcizado\nPela água benta desse olhar infindo\nQue bom é ser fotografado\nMas pela retina desses olhos lindos\nMe deixe hipnotizado\nPra acabar de vez com essa disritmia\n\nVem logo, vem curar teu nego\nQue chegou de porre...",
  // 16. Letra de 16.txt
  "O meu coração hoje tem paz\nDecepção ficou pra trás\nEu encontrei um grande amor\nFelicidade, enfim, chegou\n\nComo o brilho do luar\nEm sintonia com o mar\nNessa viagem de esplendor\nMeu sonho se realizou\n\nA gente se fala no olhar (no olhar)\nÉ água de chuva no mar (no mar)\nCaminha pro mesmo lugar\nSem pressa, sem medo de errar\nÉ tão bonito, é tão bonito o nosso amor\n\nA gente tem tanto querer (querer)\nFaz até a terra tremer (tremer)\nA luz que reluz meu viver\nO Sol do meu amanhecer é você\n\nO meu coração hoje tem paz\nDecepção ficou pra trás\nEu encontrei um grande amor\nFelicidade, enfim, chegou\n\nComo o brilho do luar\nEm sintonia com o mar\nNessa viagem de esplendor\nMeu sonho se realizou\n\nA gente se fala no olhar (no olhar)\nÉ água de chuva no mar (no mar)\nCaminha pro mesmo lugar\nSem pressa, sem medo de errar\nÉ tão bonito, é tão bonito o nosso amor\n\nA gente tem tanto querer (querer)\nFaz até a terra tremer (tremer)\nA luz que reluz meu viver\nO Sol do meu amanhecer é você\nÉ você meu bem querer\n\nA gente se fala no olhar (no olhar)\nÉ água de chuva no mar (no mar)\nCaminha pro mesmo lugar\nSem pressa...",
  // 17. Letra de 17.txt
  "Só mesmo o tempo\nPode revelar o lado oculto das paixões\nO que se foi\nE o que não passará\nInesquecíveis sensações\nQue sempre vão ficar\nPra nos fazer lembrar\nDos sonhos, beijos\nTantos momentos bons\n\nSó mesmo o tempo\nVai poder provar\nA eternidade das canções\nA nossa música está no ar\nEmocionando os corações\nPois tudo que é amor\nParece com você\nPense, lembre\nNunca vou te esquecer\n\nVou ter sempre você comigo\nNosso amor eu canto e cantarei\nVocê é tudo que eu amei na vida\nNunca vou te esquecer\n\nSó mesmo o tempo\nPode revelar o lado oculto das paixões\nO que se foi\nE o que não passará\nInesquecíveis sensações\nQue sempre vão ficar\nPra nos fazer lembrar\nDos sonhos, beijos\nTantos momentos bons",
  // 18. Letra de 18.txt
  "Eu não queria um iPhone, só tempo pra te ligar\nNem o carro do ano, só tempo pra passear\nNão quero brinco de ouro, pulseira, anel e colar\nNem o melhor vestido se não for pra te encontrar\nSó quero a liberdade de onde eu for te levar\nPegar na sua mão e se eu quiser te abraçar\nNão faço questão que você pague a conta do jantar\nDeixa pra mim, que eu mesma pago a conta do bar\n\nQue do jeito que olha pra mim\nDo jeito que eu gosto de ver\nO jeito que vive aqui\nO jeito que eu vivo em você\nO jeito é nós até o fim\nNão vou nem querer saber de nada além de nós ali\n\nDo jeito que olha pra mim\nDo jeito que eu gosto de ver\nO jeito que vive aqui\nO jeito que eu vivo em você\nO jeito é nós até o fim\nNão vou nem querer saber de nada além de nós ali\n\nEu não quero a boate, só a pista pra poder dançar (com você)\nEu não quero igreja, mas vou te levar no altar (pro cê vê)\nEu quero a beleza de ter tempo pra te amar (por quê?)\nO tempo é precioso demais pra deixar passar (sem você)\nMe diz o que será do mundo diante de nós\nNós dois somos um só, reluzindo como cristais\nBrilhando muito mais juntos do que quando sem nós\nTe sinto perto e, quando eu canto, você fica bem\n\nDo jeito que olha pra mim\nDo jeito que eu gosto de ver\nO jeito que vive aqui\nO jeito que eu vivo...",
  // 19. Letra de 19.txt
  "Talvez eu goste ainda mais de nós\nNum dia inteiro colados, a sós\nCom tempo pra se discorrer a dois\nSentir sua pele sem tua roupa\n\nNão ligo se faz frio ou faz calor\nHoje, quem me ligar, digo que tô\nNas nuvens de um poeta ou algo assim\nTorcendo pra não ser mentira\n\nEnquanto você dorme, eu cheiro você\nPra guardar na memória o tom\nDo meu veludo cor marrom, ai\nEu não tô a fim de desgrudar\nMas quero fazer, dos dias, a paz\nPara fazer um escarcéu com teu sorriso\nNem ligo, a gente pode demorar\n\nTalvez eu goste ainda mais de nós\nNum dia inteiro colados, a sós\nCom tempo pra se discorrer a dois\nSentir sua pele sem tua roupa\n\nNão ligo se faz frio ou faz calor\nHoje, quem me ligar, digo que tô\nNas nuvens de um poeta ou algo assim\nTorcendo pra não ser mentira\n\nEnquanto você dorme, eu cheiro você\nPra guardar na memória o tom\nDo meu veludo cor marrom, ai\nEu não tô a fim de desgrudar\nMas quero fazer, dos dias, a paz\nPara fazer um escarcéu com teu sorriso\nNem ligo, a gente pode demorar\n\nTalvez eu goste ainda mais de nós\nNum dia inteiro colados, a sós\nCom tempo pra se discorrer a dois\nSentir tua pele sem tua roupa\n\nNão ligo se faz frio...",
  // 20. Letra de 20.txt
  "You don't know, babe\nWhen you hold me\nAnd kiss me slowly\nIt's the sweetest thing\nAnd it don't change\nIf I had it my way\nYou would know that you are\n\nYou're the coffee that I need in the morning\nYou're my sunshine in the rain when it's pouring\nWon't you give yourself to me?\nGive it all, oh\nI just wanna see\n\nI just wanna see how beautiful you are\nYou know that I see it\nI know you're a star\nWhere you go, I follow\nNo matter how far\nIf life is a movie\nOh, you're the best part, oh\nYou're the best part, oh\nBest part\n\nIt's this sunrise\nAnd those brown eyes, yes\nYou're the one that I desire\nWhen we wake up\nAnd then we make love\nIt makes me feel so nice\n\nYou're my water when I'm stuck in the desert\nYou're the Tylenol I take when my head hurts\nYou're the sunshine on my life\n\nI just wanna see how beautiful you are\nYou know that I see it\nI know you're a star\nWhere you go, I follow\nNo matter how far\nIf life is a movie\nThen you're the best part, oh\nYou're the best part, oh\nBest part\n\nIf you love me, won't you say something?\nIf you love me, won't you, won't you\nIf you..."
];